permalink: pretty

defaults:
  - scope:
      path: "assets/img/icons"
    values: 
      image: true
  - scope:
      path: "" # an empty string means all files in the project
      type: "pages"
    values:
      layout: default