backend:
  name: github
  repo: ux-at-icfnext/cwig # Path to your GitHub repository
  netlify.configure({'site_id': cwig-pattern-library.netlify.app);
  # optional, defaults to master
  branch: main

media_folder: "assets/img/prototype"

collections:
  - label: "Basic Pages"
    name: "Baisc Pages"
    folder: "pages/prototype/basic"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "prototype/basic"}
      - {label: "category", name: "category", widget: "hidden", default: "prototype"}
      - {label: "Page Title", name: "title", widget: "string", required: true}
      - {label: "Intro Text", name: "intro", widget: "string", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show Header?", name: "header", widget: "boolean", default: false}
      - {label: "Show Get Help", name: "help", widget: "boolean", default: false}
      - {label: "Show Spanish CTA?", name: "spanish", widget: "boolean", default: false}
      - {label: "button text", name: "button", widget: "hidden", default: "Español"}
  - label: "Topic Pages"
    name: "Topic Pages"
    folder: "pages/prototype/topic-pages"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "prototype/proto-topic"}
      - {label: "category", name: "category", widget: "hidden", default: "prototype"}
      - {label: "Page Title", name: "title", widget: "string", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Card Schema"
        name: "cards"
        widget: "list"
        fields:
          - { label: "Title", name: "card-title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "text", hint: "140 characters max" }
          - { label: "Button label", name: "button", widget: "string", required: false}
          - { label: "Link", name: "link", widget: "string", required: false}
  - label: "Sub Topic"
    name: "Sub Topic"
    folder: "pages/prototype/sub-topics"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "prototype/sub-topic"}
      - {label: "category", name: "category", widget: "hidden", default: "prototype"}
      - {label: "Page Title", name: "title", widget: "string", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Featured Items"
        name: "cards"
        widget: "list"
        fields:
          - { label: "Title", name: "card-title", widget: "string" }
          - { label: "Body", name: "body", widget: "text", hint: "140 characters max" }
      - {label: "Show related links in accordion?", name: "footer-accordion", widget: "boolean", default: false}
      - label: "Related Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Link text", name: "title", widget: "string" }
          - { label: "Card Body", name: "body", widget: "string", hint: "This is only needed for accordion option"}
      - label: "You may also like links"
        name: "ymal"
        widget: "list"
        fields:
          - { label: "Link text", name: "title", widget: "string" }
          - { label: "Card Body", name: "body", widget: "string", hint: "This is only needed for accordion option"}
        
